# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e5a60f56d96ca09e9b6e71247ebd796f51f27676e00afc4c48ef942a660d1f73b5787f2ff46d5d2bf729f0044e39b5aa45818c2574b129c6c0c870817fc25be

test:
  secret_key_base: 75a4f06b379114368f5354cede4a8b8f1f7779911bc144dd3399d912c6de3daf2b65686c8ed09206eb043c969f868f54a119c6d81d2c1e207649630ef49e10e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
